version: '3.8'
services:
  app:
    build: .
    container_name: weather_app_dev
    ports: [ "5173:5173", "3001:3001" ]
    volumes:
      - ./api:/app/api
      - ./client:/app/client
      - /app/api/node_modules
      - /app/client/node_modules
    env_file: [ ./api/.env ]
    depends_on: [ mongo ]
    networks: [ weather-net ]
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports: [ "27017:27017" ]
    volumes: [ ./docker-data/db:/data/db ]
    networks: [ weather-net ]
networks:
  weather-net:
    driver: bridge
